[2025-09-12T03:23:10.034+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: aviationstack_kafka_dag.run_kafka_consumer manual__2025-09-12T03:23:08.009268+00:00 [queued]>
[2025-09-12T03:23:10.037+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: aviationstack_kafka_dag.run_kafka_consumer manual__2025-09-12T03:23:08.009268+00:00 [queued]>
[2025-09-12T03:23:10.037+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-12T03:23:10.041+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_kafka_consumer> on 2025-09-12 03:23:08.009268+00:00
[2025-09-12T03:23:10.042+0000] {standard_task_runner.py:60} INFO - Started process 194 to run task
[2025-09-12T03:23:10.044+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'aviationstack_kafka_dag', 'run_kafka_consumer', 'manual__2025-09-12T03:23:08.009268+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/aviationstack_dag.py', '--cfg-path', '/tmp/tmp7vz55idx']
[2025-09-12T03:23:10.045+0000] {standard_task_runner.py:88} INFO - Job 15: Subtask run_kafka_consumer
[2025-09-12T03:23:10.063+0000] {task_command.py:423} INFO - Running <TaskInstance: aviationstack_kafka_dag.run_kafka_consumer manual__2025-09-12T03:23:08.009268+00:00 [running]> on host f8e9c153be16
[2025-09-12T03:23:10.087+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='aviationstack_kafka_dag' AIRFLOW_CTX_TASK_ID='run_kafka_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-09-12T03:23:08.009268+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-12T03:23:08.009268+00:00'
[2025-09-12T03:23:10.088+0000] {logging_mixin.py:188} INFO - Starting consumer...
[2025-09-12T03:23:10.090+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-12T03:23:10.090+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-12T03:23:10.090+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. 
[2025-09-12T03:23:10.408+0000] {cluster.py:401} INFO - Coordinator for group/aviation_flight_data_test_group_02 is ('coordinator-1', 'kafka', 9092, None)
[2025-09-12T03:23:10.408+0000] {base.py:788} INFO - Discovered coordinator coordinator-1 for group aviation_flight_data_test_group_02
[2025-09-12T03:23:10.408+0000] {base.py:848} INFO - Starting new heartbeat thread
[2025-09-12T03:23:10.409+0000] {consumer.py:365} INFO - Revoking previously assigned partitions () for group aviation_flight_data_test_group_02
[2025-09-12T03:23:10.409+0000] {base.py:419} INFO - Failed to join group aviation_flight_data_test_group_02: NodeNotReadyError: coordinator-1
[2025-09-12T03:23:10.410+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-12T03:23:10.410+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-12T03:23:10.516+0000] {base.py:532} INFO - (Re-)joining group aviation_flight_data_test_group_02
[2025-09-12T03:23:10.524+0000] {base.py:637} INFO - Received member id kafka-python-2.2.15-bac0b038-73ff-4415-b94c-3597631df95c for group aviation_flight_data_test_group_02; will retry join-group
[2025-09-12T03:23:10.524+0000] {base.py:419} INFO - Failed to join group aviation_flight_data_test_group_02: [Error 79] MemberIdRequiredError
[2025-09-12T03:23:10.525+0000] {base.py:532} INFO - (Re-)joining group aviation_flight_data_test_group_02
[2025-09-12T03:23:13.548+0000] {base.py:594} INFO - Successfully joined group aviation_flight_data_test_group_02 <Generation 1 (member_id: kafka-python-2.2.15-bac0b038-73ff-4415-b94c-3597631df95c, protocol: range)>
[2025-09-12T03:23:13.548+0000] {base.py:596} INFO - Elected group leader -- performing partition assignments using range
[2025-09-12T03:23:13.562+0000] {subscription_state.py:254} INFO - Updated partition assignment: [('aviation_flight_data', 0)]
[2025-09-12T03:23:13.563+0000] {consumer.py:249} INFO - Setting newly assigned partitions (('aviation_flight_data', 0),) for group aviation_flight_data_test_group_02
[2025-09-12T03:23:13.569+0000] {fetcher.py:418} INFO - Resetting offset for partition ('aviation_flight_data', 0) to offset 1.
[2025-09-12T03:23:20.089+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-09-12T03:23:20.104+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=aviationstack_kafka_dag, task_id=run_kafka_consumer, execution_date=20250912T032308, start_date=20250912T032310, end_date=20250912T032320
[2025-09-12T03:23:20.119+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-12T03:23:20.132+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
