[2025-09-16T06:53:29.113+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: opensky_data_pipeline_dag.run_kafka_consumer_slow manual__2025-09-16T06:53:28.631311+00:00 [queued]>
[2025-09-16T06:53:29.115+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: opensky_data_pipeline_dag.run_kafka_consumer_slow manual__2025-09-16T06:53:28.631311+00:00 [queued]>
[2025-09-16T06:53:29.116+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-16T06:53:29.119+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_kafka_consumer_slow> on 2025-09-16 06:53:28.631311+00:00
[2025-09-16T06:53:29.122+0000] {standard_task_runner.py:60} INFO - Started process 415 to run task
[2025-09-16T06:53:29.123+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'opensky_data_pipeline_dag', 'run_kafka_consumer_slow', 'manual__2025-09-16T06:53:28.631311+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/opensky_data_pipeline_dag.py', '--cfg-path', '/tmp/tmpwgmsngyb']
[2025-09-16T06:53:29.125+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask run_kafka_consumer_slow
[2025-09-16T06:53:29.146+0000] {task_command.py:423} INFO - Running <TaskInstance: opensky_data_pipeline_dag.run_kafka_consumer_slow manual__2025-09-16T06:53:28.631311+00:00 [running]> on host 7b6d608462af
[2025-09-16T06:53:29.177+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='opensky_data_pipeline_dag' AIRFLOW_CTX_TASK_ID='run_kafka_consumer_slow' AIRFLOW_CTX_EXECUTION_DATE='2025-09-16T06:53:28.631311+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-16T06:53:28.631311+00:00'
[2025-09-16T06:53:29.179+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-16T06:53:29.181+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.4', 9092)]>: Broker version identified as 2.6
[2025-09-16T06:53:29.181+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-16T06:53:29.182+0000] {subscription_state.py:181} INFO - Updating subscribed topics to: ('opensky_data',)
[2025-09-16T06:53:29.183+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-16T06:53:29.183+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-16T06:53:29.183+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. 
[2025-09-16T06:53:29.502+0000] {cluster.py:401} INFO - Coordinator for group/opensky_full_pipeline_consumer_01 is ('coordinator-1', 'kafka', 9092, None)
[2025-09-16T06:53:29.502+0000] {base.py:788} INFO - Discovered coordinator coordinator-1 for group opensky_full_pipeline_consumer_01
[2025-09-16T06:53:29.502+0000] {base.py:848} INFO - Starting new heartbeat thread
[2025-09-16T06:53:29.503+0000] {consumer.py:365} INFO - Revoking previously assigned partitions () for group opensky_full_pipeline_consumer_01
[2025-09-16T06:53:29.503+0000] {base.py:419} INFO - Failed to join group opensky_full_pipeline_consumer_01: NodeNotReadyError: coordinator-1
[2025-09-16T06:53:29.503+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-16T06:53:29.503+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-16T06:53:29.605+0000] {base.py:532} INFO - (Re-)joining group opensky_full_pipeline_consumer_01
[2025-09-16T06:53:29.607+0000] {base.py:637} INFO - Received member id kafka-python-2.2.15-8ecd4fbb-b0fd-4a58-90af-55e70a52069c for group opensky_full_pipeline_consumer_01; will retry join-group
[2025-09-16T06:53:29.607+0000] {base.py:419} INFO - Failed to join group opensky_full_pipeline_consumer_01: [Error 79] MemberIdRequiredError
[2025-09-16T06:53:29.607+0000] {base.py:532} INFO - (Re-)joining group opensky_full_pipeline_consumer_01
[2025-09-16T06:53:35.628+0000] {base.py:594} INFO - Successfully joined group opensky_full_pipeline_consumer_01 <Generation 1 (member_id: kafka-python-2.2.15-8ecd4fbb-b0fd-4a58-90af-55e70a52069c, protocol: range)>
[2025-09-16T06:53:35.640+0000] {subscription_state.py:254} INFO - Updated partition assignment: [('opensky_data', 0)]
[2025-09-16T06:53:35.640+0000] {consumer.py:249} INFO - Setting newly assigned partitions (('opensky_data', 0),) for group opensky_full_pipeline_consumer_01
[2025-09-16T06:53:35.646+0000] {fetcher.py:418} INFO - Resetting offset for partition ('opensky_data', 0) to offset 0.
[2025-09-16T06:53:36.277+0000] {kafka_consumer.py:40} INFO - Saved payload to data/kafka_logs/opensky/as_message_20250916_065336.json
[2025-09-16T06:53:36.277+0000] {kafka_consumer.py:45} INFO - Saved payload to data/kafka_logs/opensky/as_message_20250916_065336.json
[2025-09-16T06:53:36.277+0000] {python.py:201} INFO - Done. Returned value was: data/kafka_logs/opensky/as_message_20250916_065336.json
[2025-09-16T06:53:36.287+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=opensky_data_pipeline_dag, task_id=run_kafka_consumer_slow, execution_date=20250916T065328, start_date=20250916T065329, end_date=20250916T065336
[2025-09-16T06:53:36.332+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-16T06:53:36.342+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
