[2025-09-12T03:36:23.211+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: aviationstack_kafka_dag.run_kafka_consumer manual__2025-09-12T03:36:21.330312+00:00 [queued]>
[2025-09-12T03:36:23.214+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: aviationstack_kafka_dag.run_kafka_consumer manual__2025-09-12T03:36:21.330312+00:00 [queued]>
[2025-09-12T03:36:23.214+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-12T03:36:23.218+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_kafka_consumer> on 2025-09-12 03:36:21.330312+00:00
[2025-09-12T03:36:23.221+0000] {standard_task_runner.py:60} INFO - Started process 249 to run task
[2025-09-12T03:36:23.223+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'aviationstack_kafka_dag', 'run_kafka_consumer', 'manual__2025-09-12T03:36:21.330312+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/aviationstack_dag.py', '--cfg-path', '/tmp/tmpxw0ccz0s']
[2025-09-12T03:36:23.224+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask run_kafka_consumer
[2025-09-12T03:36:23.245+0000] {task_command.py:423} INFO - Running <TaskInstance: aviationstack_kafka_dag.run_kafka_consumer manual__2025-09-12T03:36:21.330312+00:00 [running]> on host f4b8ac862c00
[2025-09-12T03:36:23.271+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='aviationstack_kafka_dag' AIRFLOW_CTX_TASK_ID='run_kafka_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-09-12T03:36:21.330312+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-12T03:36:21.330312+00:00'
[2025-09-12T03:36:23.272+0000] {logging_mixin.py:188} INFO - Starting consumer...
[2025-09-12T03:36:23.274+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-12T03:36:23.274+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-12T03:36:23.274+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. 
[2025-09-12T03:36:23.586+0000] {cluster.py:401} INFO - Coordinator for group/aviation_flight_data_test_group_02 is ('coordinator-1', 'kafka', 9092, None)
[2025-09-12T03:36:23.586+0000] {base.py:788} INFO - Discovered coordinator coordinator-1 for group aviation_flight_data_test_group_02
[2025-09-12T03:36:23.586+0000] {base.py:848} INFO - Starting new heartbeat thread
[2025-09-12T03:36:23.587+0000] {consumer.py:365} INFO - Revoking previously assigned partitions () for group aviation_flight_data_test_group_02
[2025-09-12T03:36:23.587+0000] {base.py:419} INFO - Failed to join group aviation_flight_data_test_group_02: NodeNotReadyError: coordinator-1
[2025-09-12T03:36:23.587+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-09-12T03:36:23.588+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-09-12T03:36:23.694+0000] {base.py:532} INFO - (Re-)joining group aviation_flight_data_test_group_02
[2025-09-12T03:36:23.703+0000] {base.py:637} INFO - Received member id kafka-python-2.2.15-d9e0daa8-0827-4577-96c0-cc2642711c9a for group aviation_flight_data_test_group_02; will retry join-group
[2025-09-12T03:36:23.703+0000] {base.py:419} INFO - Failed to join group aviation_flight_data_test_group_02: [Error 79] MemberIdRequiredError
[2025-09-12T03:36:23.704+0000] {base.py:532} INFO - (Re-)joining group aviation_flight_data_test_group_02
[2025-09-12T03:36:29.733+0000] {base.py:594} INFO - Successfully joined group aviation_flight_data_test_group_02 <Generation 1 (member_id: kafka-python-2.2.15-d9e0daa8-0827-4577-96c0-cc2642711c9a, protocol: range)>
[2025-09-12T03:36:29.753+0000] {subscription_state.py:254} INFO - Updated partition assignment: [('aviation_flight_data', 0)]
[2025-09-12T03:36:29.754+0000] {consumer.py:249} INFO - Setting newly assigned partitions (('aviation_flight_data', 0),) for group aviation_flight_data_test_group_02
[2025-09-12T03:36:29.760+0000] {fetcher.py:418} INFO - Resetting offset for partition ('aviation_flight_data', 0) to offset 2.
[2025-09-12T03:36:33.272+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-09-12T03:36:33.288+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=aviationstack_kafka_dag, task_id=run_kafka_consumer, execution_date=20250912T033621, start_date=20250912T033623, end_date=20250912T033633
[2025-09-12T03:36:33.306+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-12T03:36:33.319+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
